swagger: '2.0'
info:
  title: RDTagent API
  description: RDTagent API specification
  version: "0.0.1"
  contact:
    name: RDTagent API Support
    url: http://www.openstack-core.team.org
    email: opoenstack-core@intel.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
schemes:
  - http
basePath: /v1
produces:
  - application/json
paths:
  /cpuinfo:
     get:
      summary: Host CPU information
      description: |
        Get the CPU information, include level 2, level 3 cache information
      tags:
        - cpuinfo
      responses:
        200:
          description: CPU info
          schema:
            type: object
            properties:
              cpuinfo:
                $ref: '#/definitions/CpuInfo'
  /cpuinfo/topology:
    get:
      summary: Host CPU topology
      description: |
        Get the CPU topology information of sockets, core and thread in each core on the host machine.
      tags:
        - cpuinfo
      responses:
        200:
          description: An array of CPU topology object
          schema:
            type: array
            items:
              $ref: '#/definitions/CpuSocket'
  /cpuinfo/capabilities:
    get:
      summary: Get the capacities of host
      description: |
        Get the capacities of the cache, memory
      tags:
        - cpuinfo
      responses:
        200:
          description: CPU capacities object
          schema:
            type: object
            properties:
              caps:
                $ref: '#/definitions/Caps'
  /cache/l3/usage:
    get:
      summary: Get the l3 cache usage of specified processes
      description: |
        Get the l3 cache usage of specified processes
      tags:
        - cmt
      parameters:
        - name: process-list
          in: query
          description: process list of cache usage
          required: false
          type: string
        - name: core-list
          in: query
          description: core list of cache usage
          required: false
          type: string
      responses:
        200:
          description: l3 cache size usage in KiB
          schema:
            type: integer
            format: int32
        400:
          description: Bad request
        404:
          description: Not found
  /memory/usage:
    get:
      summary: Get Memory bandwidth specified processes or cores
      description: |
        Get the l3 cache usage of specified processes
      tags:
        - mbm
      parameters:
        - name: process-id
          in: query
          description: process list of memory bandwidth
          required: false
          type: string
        - name: core-list
          in: query
          description: core list of memory bandwidth
          required: false
          type: string
        - name: interval
          in: query
          description: query interval
          type: integer
          format: int32
      responses:
        200:
          description: Memory bandwidth thought interval
          schema:
            type: integer
            format: int32
        400:
          description: Bad request
        404:
          description: Not found
  /cache/l3/alloc:
    post:
      summary: Create l3 cache allocation
      description: |
        create l3 cache allocation for specified process
      tags:
        - cat
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: string
            example:
              process-id: 1234
              cache-size: 1024
      responses:
        202:
          description: accepted
        400:
          description: bad request
  /cache/cos/{socket-id}:
    get:
      summary: Get cos on specified socket id
      description: |
        Get Class of service on speicified socket id
      tags:
        - cat
      parameters:
      - name: socket-id
        in: path
        description: ID of Socket of clos to get
        required: true
        type: array
        items:
          type: integer
          format: int32
      responses:
        200:
          description: clos on specified socket
          schema:
            type: array
            items:
              type: string
        400:
          description: Bad request
        404:
          description: Not found
  /cache/cos/{socket-id}/{cos-id}:
    get:
      summary: Get cos on specified socket id and cos id
      description: |
        Get Class of service on speicified socket id
      tags:
        - cat
      parameters:
      - name: socket-id
        in: path
        description: ID of Socket of clos to get
        required: true
        type: integer
        format: int32
      - name: cos-id
        in: path
        description: ID of COS
        required: true
        type: integer
        format: int32
      responses:
        200:
          description: cos on specified socket and cos ID
          schema:
            type: string
        400:
          description: Bad request
        404:
          description: Not found
    put:
      summary: Create cos
      description: |
        create cos on specificed socket
      tags:
        - cat
      parameters:
        - name: socket-id
          in: path
          description: ID of Socket of clos to get
          required: true
          type: integer
          format: int32
        - name: cos-id
          in: path
          description: ID of COS
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          required: true
          schema:
            type: string
            example:
              cos_id: 0
              cos_mask: '0xfffff'
              socket_id: 0
      responses:
        200:
          description: created
        400:
          description: bad request
        404:
          description: socket id not found on host
  /cache/cos:
    get:
      summary: Get all cos of the host
      description: |
        Get Class of service on host
      tags:
        - cat
      responses:
        200:
          description: clos on specified socket
          schema:
            type: array
            items:
              type: string
        400:
          description: Bad request
        404:
          description: Not found

definitions:
  Cacheinfo:
    type: object
    properties:
      cache_level:
        type: string
        enum: ['l3', 'l2']
        description: cache level, could be l3/l2
      cache_size:
        type: integer
        format: int32
        description: cache size in KiB
      cache_way:
        type: string
        description: cache way
  CpuInfo:
    type: object
    properties:
      cpu_num:
        description: How many cpu on the host
        type: integer
        format: int32
      l2_cache:
        $ref: '#/definitions/Cacheinfo'
      l3_cache:
        $ref: '#/definitions/Cacheinfo'
  Cpu:
    type: object
    properties:
      cpu_id:
        type: string
        description: Cpu id
  Core:
    type: object
    properties:
      core_id:
        type: string
        description: Cpu core id
      cpus:
        type: array
        items:
          $ref: '#/definitions/Cpu'
  CpuSocket:
    type: object
    properties:
      socket_id:
        type: string
        description: Socket id of the physical CPU
      cores:
        type: array
        description: Core list located on the physical CPU
        items:
          $ref: '#/definitions/Core'
  Capability:
    type: object
    description: RDT capabilitiy
    properties:
      cap_type:
        type: string
        description: capablities type
      meta:
        description: This is a string, each type of capability may different, we will format it later
        type: string
  Caps:
    type: object
    properties:
      num_cap:
        description: how many capabilies can be discovered
        type: integer
        format: int32
      capabilities:
        type: array
        items:
          $ref: '#/definitions/Capability'
