#!/usr/bin/env bash

if [ ! -f install-deps ]; then
	echo 'This script must be run within its container folder' 1>&2
	exit 1
fi

go fmt
godep go install github.com/intel/rmd && \
sudo cp -r etc/rmd /etc

USER="rmd"
sudo useradd $USER || echo "User rmd already exists."

LOGFILE="/var/log/rmd/rmd.log"
if [ ! -d ${LOGFILE%/*} ]; then
    sudo mkdir -p ${LOGFILE%/*}
    sudo chown $USER:$USER ${LOGFILE%/*}
fi

DBFILE="/var/run/rmd/rmd.db"
if [ ! -d ${DBFILE%/*} ]; then
    sudo mkdir -p ${DBFILE%/*}
    sudo chown $USER:$USER  ${DBFILE%/*}
fi

sudo ./setup_pam_files.sh

DATA="\"logfile\":\"$LOGFILE\", \"dbtransport\":\"$DBFILE\", \"logtostdout\":false"
go run ./cmd/gen_conf.go -path /etc/rmd/rmd.toml -data "{$DATA}"
