#!/usr/bin/env bash

if [ ! -f install-deps ]; then
	echo 'This script must be run within its container folder' 1>&2
	exit 1
fi

go fmt
godep go install openstackcore-rdtagent
cp etc/policy.yaml $GOPATH/bin/policy.yaml
