#!/usr/bin/env bash

if [ ! -f install-deps ]; then
	echo 'This script must be run within its container folder' 1>&2
	exit 1
fi

go fmt
godep go install openstackcore-rdtagent && \
sudo mkdir /etc/rdtagent/ || \
sudo cp etc/policy.yaml /etc/rdtagent/policy.yaml
sudo cp etc/rdtagent/rdtagent.toml /etc/rdtagent/rdtagent.toml
