# This is a rmd config.

title = "RMD config"

[default]
address = "localhost"
policypath = "/etc/rmd/policy.toml"
tlsport = 8443 # requires a port number higher than 1024
# certpath = "etc/rmd/cert/server" # Only support pem format, hard code that CAFile is ca.pem, CertFile is rmd-cert.pem, KeyFile is rmd-key.pem
# clientcapath = "etc/rmd/cert/client" # Only support pem format, hard code that CAFile is ca.pem
clientauth = "challenge"  # can be "no, require, require_any, challenge_given, challenge", challenge means require and verify.
# unixsock = "./var/run/rmd.sock"

[debug]
enabled = false
debugport = 8081

[log]
path = "/var/log/rmd.log"
env = "dev"  # production or dev
level = "debug"
stdout = true

[database]
backend = "bolt" # mgo
transport = "/var/run/rmd.db" # mongodb://localhost
dbname = "bolt" # RDTPolicy


[OSGroup] # OSGroup is mandatory
cacheways = 1
cpuset = "0-1"

[InfraGroup] # InfraGroup is optional
cacheways = 19
cpuset = "2-3"
# arrary or comma-separated values? RMD supports array instead of CSV.
tasks = ["ovs*"] # Just support Wildcards. Do we need to support RE?

[CachePool] # Cache Pool config is optional
shrink = false # wether allow to shrink cache ways in best effort pool
max_allowed_shared = 10 # max allowed workload in shared pool, default is 10
guarantee = 10
besteffort = 7
shared = 2

[acl]
path = "/etc/rmd/acl/"  #
# use CSV format
filter = "url" # at present just support "url", will support "url,ip,proto"
authorization = "role" # authorize the client, can identify client by signature, role(OU) or username(CN). Default value is signature. If value is signature, admincert and usercert should be set.
admincert = "/etc/rmd/acl/roles/admin/" # A cert is used to describe user info. These cert files in this path are used to define the users that are admin. Only pem format file at present. The files can be updated dynamicly.
usercert = "/etc/rmd/acl/roles/user/" # A cert is used to describe user info. These cert files in this path are used to define the user with low privilege. Only pem format file at present. The files can be updated dynamicly.

[pam]
service = "rmd"
