# This is a rdtagent config.

title = "RDTagent Config"

[default]
address = "localhost"
port = 8081

[log]
path = "/var/log/rdagent.log"
env = "dev"  # production or dev
level = "debug"
stdout = true

[database]
backend = "bolt" # mgo
transport = "/var/run/rdtagent.db" # mongodb://localhost
dbname = "bolt" # RDTPolicy


[OSGroup] # OSGroup is mandatory
cacheways = 1
cpuset = "0-1"

[InfraGroup] # InfraGroup is optional
cacheways = 10
cpuset = "2-3"
# arrary or comma-separated values? RMD supports array instead of CSV.
tasks = ["ovs*"] # Just support Wildcards. Do we need to support RE?

[CachePool] # Cache Pool config is optional
gurantee = 12
besteffort = 7
shared = 3
