# This is a rdtagent config.

title = "RDTagent Config"

[default]
address = "localhost"
port = 8081

[log]
path = "/var/log/rdagent.log"
env = "dev"  # production or dev
level = "debug"
stdout = "false"

[database]
backend = "bolt" # mgo
transport = "/var/run/rdtagent.db" # mongodb://localhost
dbname = "bolt" # RDTPolicy


[OSGroup] # OSGroup is mandatory
cacheways = 1
cpuset = "0-1"
