# This is a rdtagent config.

title = "RDTagent Config"

[default]
address = "localhost"
port = 8081

[log]
path = "/var/log/redagent.log"
level = "debug"

[database]
transport = "/var/run/rdtagent.db"
