# This is a rdtagent config.

title = "RDTagent Config"

[default]
address = "0.0.0.0"
port = 8081

[log]
path = "/var/log/redagent.log"
level = "debug"

[database]
transport = "./etc/data/rdtagent.db" # will change it to /etc path.
